version: "3.8"
services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - mongodb
    env_file:
      - .env
    volumes:
      - ./src:/app
  mongodb:
    build:
      context: ./mongo
    ports:
      - "27017:27017"
